TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

INC += BFResolveGenTL.h
LIBRARY_IOC_Linux += GenTLInterface
LIB_SRCS_Linux += GenICamUtilities.cpp
LIB_SRCS_Linux += Port.cpp
LIB_LIBS_Linux += GCBase_gcc48_v3_3
LIB_LIBS_Linux += GenApi_gcc48_v3_3

#=============================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

