TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

INC += BFLogClientApi.h
INC += BFLogIODef.h
INC += BFUniversalDef.h

LIBRARY_IOC_Linux += BFLogIO
LIB_SRCS_Linux += BFLogClientApi.cpp
LIB_SRCS_Linux += BFLogIOMessageApi.cpp
LIB_SRCS_Linux += BFLogIOMessageClass.cpp
LIB_SRCS_Linux += BFLogIOSourceApi.cpp
LIB_SRCS_Linux += BFLogIOSourceClass.cpp
LIB_SRCS_Linux += BFLogIOSyncApi.cpp
LIB_SRCS_Linux += BFLogIOSyncClass.cpp

#=============================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

